# Generated by Django 3.0.5 on 2020-04-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('card_number', models.IntegerField()),
                ('csv', models.IntegerField()),
                ('balance', models.FloatField()),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sum', models.FloatField()),
                ('transfer_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'transfers',
                'managed': False,
            },
        ),
    ]
